"""generating visit id 

Revision ID: 319350275b77
Revises: 6e64acbbc4d0
Create Date: 2025-11-04 18:47:31.267151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '319350275b77'
down_revision: Union[str, None] = '6e64acbbc4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column('visits', 'visit_id',
                    existing_type=sa.String(),
                    nullable=True
                    )


def downgrade():
    op.alter_column('visits', 'visit_id',
                    existing_type=sa.String(),
                    nullable=False
                    )

# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index('ix_visits_id', table_name='visits')
#     op.drop_index('ix_visits_visit_id', table_name='visits')
#     op.drop_table('visits')
#     op.drop_index('ix_patients_id', table_name='patients')
#     op.drop_index('ix_patients_patient_id', table_name='patients')
#     op.drop_table('patients')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('patients',
#     sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('patients_id_seq'::regclass)"), autoincrement=True, nullable=False),
#     sa.Column('patient_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
#     sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
#     sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
#     sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
#     sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
#     sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
#     sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('emergency_contact', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
#     sa.Column('medical_history', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('current_medications', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('id', name='patients_pkey'),
#     postgresql_ignore_search_path=False
#     )
#     op.create_index('ix_patients_patient_id', 'patients', ['patient_id'], unique=True)
#     op.create_index('ix_patients_id', 'patients', ['id'], unique=False)
#     op.create_table('visits',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('visit_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
#     sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('visit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
#     sa.Column('visit_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
#     sa.Column('chief_complaint', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('symptoms', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('diagnosis', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('treatment_plan', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('medications_prescribed', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('follow_up_instructions', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('doctor_notes', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('vital_signs', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('lab_results', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='visits_patient_id_fkey'),
#     sa.PrimaryKeyConstraint('id', name='visits_pkey')
#     )
#     op.create_index('ix_visits_visit_id', 'visits', ['visit_id'], unique=True)
#     op.create_index('ix_visits_id', 'visits', ['id'], unique=False)
#     # ### end Alembic commands ###
